[tool.poetry]
name = "ipinfo"
version = "0.0.1"
description = ""
authors = ["dadevel"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
maxminddb = "^2.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
